baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "My Secure Hugo Portfolio"
theme = "ananke"

[params]
  description = "Secure Hugo Portfolio"
  author = "Ziad Naciri"

[menus]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4
