baseURL = "https://ziad-naciri.netlify.app/"
languageCode = "en-us"
title = "Ziad Naciri | Portfolio"
theme = "raditian"


#Theme Module 
[module]
  [[module.imports]]
    path = "github.com/radity/raditian-free-hugo-theme"

# Plugins
[params.plugins]

# CSS Plugins
[[params.plugins.css]]
  URL = "/css/main.css"
[[params.plugins.css]]
  URL = "/css/rad-icons.css"
[[params.plugins.css]]
  URL = "/css/custom.css"

# JS Plugins
[[params.plugins.js]]
  URL = "/js/rad-animations.js"
[[params.plugins.js]]
  URL = "/js/sticky-header.js"
[[params.plugins.js]]
  URL = "/js/library/fontfaceobserver.js"

# navigation
[menu]
  [[menu.header]]
  name = "Home"
  URL = "#home"
  weight = 1
  
  [[menu.header]]
  name = "About"
  URL = "#about"
  weight = 2

  [[menu.header]]
  name = "Projects"
  URL = "#portfolio"
  weight = 3

  [[menu.header]]
  name = "Contact"
  URL = "#contact"
  weight = 4


  [[menu.footer]]
  name = "About"
  URL = "#about"
  weight = 2

  [[menu.footer]]
  name = "Projects"
  URL = "#portfolio"
  weight = 3

  [[menu.footer]]
  name = "Contact"
  URL = "#contact"
  weight = 4


[params]
  sections = ["showcase", "about", "education", "experience","client-and-work", "contact"]
  googleTagManagerID = "GTM-000000" # Google Analytics works with Google Tag Manager

  [params.logo]
    text1 = "Naciri"
    text2 = "Ziad"

  [params.footer]
        copyright = " © Raditian"
        author = "Ziad Naciri"
        [params.footer.radity_logo]
        x = "img/general/design-and-code-radity.png"
        _2x = "img/general/design-and-code-radity@2x.png"
        alt = "Design & Code - Radity"
        
# security headers
[[server.headers]]
  for = '/**'
  [server.headers.values]
    Content-Security-Policy = '''
      default-src 'self' http://localhost:1313;
      script-src 'self' 'unsafe-hashes' http://localhost:1313 https://www.google.com/recaptcha/api.js https://www.gstatic.com/recaptcha/releases/lqsTZ5beIbCkK4uGEGv9JmUR/recaptcha__en.js 'sha256-ZUBnUDfsX/mhVi0F0de6Opxnc1S4t7vaSqZs0/XW+R0=' 'sha256-AcZHBRd1XuxlEnarbX/geO9CkqhjUcvk6yLPqe+p2Nw=' 'sha256-0HI3nX1RARjFCqzL9ivUeKOYwI+pzT3ArGHEWpZvntE=';
      style-src 'self' 'unsafe-hashes' http://localhost:1313 'sha256-+sqQHf8rxT096ZQ9VWHKpYDYKFgKHuXqAZFwjNkoN4o=' 'sha256-cUMPOnX0WtlUKrw+/R5VCI3qjs/AWY5gK+dmAMXdwKs=' 'sha256-ePAfP+mBzf8gl35Rk9/S9+iTHFcaqlh8RAg+sIQK8D0=' 'sha256-OLjQZuNLrofgRx4Dof0UewFKTRILJwrytJD7Mi/Pnj8=' 'sha256-xVEK7gcaeJAqZHgUjP0ktYmyVcW5brxPqD47mQeu5uw=' 'sha256-c4Oga/RiXVo9o/jXx8Awar60XCk/14unWIuJn3ADXoM=' 'sha256-CaW5ag67LQMx6MNoV1YygREmDA0MUfWUPNliIv9Yu9I=' 'sha256-lqaUTp4AFIo+P2WUs81N56QrKUfr0hkCPnj7cX5YE1I=' 'sha256-FkzUySBbFSseDEQBJ+4mR6Yr6icVGf+h59BjeTFkj7c=' 'sha256-7iPNlaODM66q5HCworTsCb1Aso8wnHf/2T6uP/ci4x4=';
      img-src 'self' data:;
      connect-src 'self' http://localhost:1313;
      font-src 'self';
      frame-src 'none';
      object-src 'none';
      base-uri 'self';
      form-action 'self';
    '''
    Referrer-Policy = 'strict-origin-when-cross-origin'
    X-Content-Type-Options = 'nosniff'
    X-Frame-Options = 'DENY'
    X-XSS-Protection = '1; mode=block'
