baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Portfolio'
theme = 'ananke'

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2
