# security headers
[[headers]]
    for = '/**'
    [headers.values]
    Content-Security-Policy = '''
      default-src 'self' https://ziad-naciri.netlify.app;
      script-src 'self' 'unsafe-hashes' https://ziad-naciri.netlify.app 'sha256-ZUBnUDfsX/mhVi0F0de6Opxnc1S4t7vaSqZs0/XW+R0=' 'sha256-AcZHBRd1XuxlEnarbX/geO9CkqhjUcvk6yLPqe+p2Nw=' 'sha256-0HI3nX1RARjFCqzL9ivUeKOYwI+pzT3ArGHEWpZvntE=';
      style-src 'self' 'unsafe-hashes' https://ziad-naciri.netlify.app 'sha256-+sqQHf8rxT096ZQ9VWHKpYDYKFgKHuXqAZFwjNkoN4o=' 'sha256-cUMPOnX0WtlUKrw+/R5VCI3qjs/AWY5gK+dmAMXdwKs=' 'sha256-ePAfP+mBzf8gl35Rk9/S9+iTHFcaqlh8RAg+sIQK8D0=' 'sha256-OLjQZuNLrofgRx4Dof0UewFKTRILJwrytJD7Mi/Pnj8=' 'sha256-xVEK7gcaeJAqZHgUjP0ktYmyVcW5brxPqD47mQeu5uw=' 'sha256-c4Oga/RiXVo9o/jXx8Awar60XCk/14unWIuJn3ADXoM=' 'sha256-CaW5ag67LQMx6MNoV1YygREmDA0MUfWUPNliIv9Yu9I=' 'sha256-lqaUTp4AFIo+P2WUs81N56QrKUfr0hkCPnj7cX5YE1I=' 'sha256-FkzUySBbFSseDEQBJ+4mR6Yr6icVGf+h59BjeTFkj7c=' 'sha256-7iPNlaODM66q5HCworTsCb1Aso8wnHf/2T6uP/ci4x4=';
      img-src 'self' data:;
      connect-src 'self' https://ziad-naciri.netlify.app;
      font-src 'self';
      frame-src 'self' https://ziad-naciri.netlify.app;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
    '''
    Referrer-Policy = 'strict-origin-when-cross-origin'
    X-Content-Type-Options = 'nosniff'
    X-Frame-Options = 'DENY'
    X-XSS-Protection = '1; mode=block'
