# security headers
[[headers]]
    for = '/**'
    [headers.values]
      Content-Security-Policy = '''
        default-src 'self';
        script-src 'self' 'unsafe-inline' 'unsafe-eval' https://ziad-naciri.netlify.app;
        style-src 'self' 'unsafe-inline';
        img-src 'self' data:;
        connect-src 'self' https://ziad-naciri.netlify.app;
        font-src 'self';
        frame-src 'none';
        object-src 'none';
        base-uri 'self';
        form-action 'self';
      '''
      Referrer-Policy = 'strict-origin-when-cross-origin'
      X-Content-Type-Options = 'nosniff'
      X-Frame-Options = 'DENY'
      X-XSS-Protection = '1; mode=block'
