security:
# Content Security Policy (CSP) settings
csp:
  # Define the CSP policy
  policy: "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' https:; object-src 'none'; frame-ancestors 'none'; base-uri 'self'; form-action 'self';"
  # Set to false to enforce the policy, true to only report violations
  report_only: false

# Permissions Policy settings
permissions:
  # Define the Permissions Policy to control which features can be used
  policy: "geolocation=(), camera=()"
